<div style="background-color: lightblue; padding: 40px; font-size: 40px;">
            K-Nearest Neighbor
</div>

- KNN algorithm is a supervised Algorithm that makes predictions based on how close a new data point 
is to known data points.

- Predictions are made for a new data point by searching through the entire training set for the K most similar instances (the neighbors) and summarizing the output variable for those K instances. For regression problems, this might be the mean output variable. For classification problems this might be the mode (or most common) class value.

 - Pros:
Simple
Robust to noise
Effective with large datasets
Performs calculations "just in time"
Data is easy to keep up to date to keep predictions accurate


 - Cons:
Need to determine how many neighbors is optimal
Computation cost is high (has to calculate every single distance to every feature)
Euclidean volume increases exponentially as number of features increases (curse of dimensionality)

In [3]:
#Tabular data imports:
import numpy as np
import pandas as pd

# Imports we need for assessing the performance of our model:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import MinMaxScaler

#User-Defined Function-importing the functions for fetching the data:
import acquire
#User-Defined Function-importing functions for prepping the data that's fetched and for splitting the data:
import prepare
#User-Defined Function-importing the functions for classification_metrics
import evaluate

# Acquire & Prepare Data

In [4]:
# Acquire data
titanic = prep_titanic_for_dt(new_titanic_data())
titanic.head()

survived  age  sibsp  parch     fare  alone  Cherbourg  Queenstown  \
0         0   22      1      0   7.2500      0          0           0   
1         1   38      1      0  71.2833      0          1           0   
2         1   26      0      0   7.9250      1          0           0   
3         1   35      1      0  53.1000      0          0           0   
4         0   35      0      0   8.0500      1          0           0   

   Southampton  female  male  
0            1       0     1  
1            0       1     0  
2            1       1     0  
3            1       1     0  
4            1       0     1

In [48]:
# Train, validate, split data
train, validate, test = split_function(titanic, 'survived')

In [49]:
train.head()

survived  age  sibsp  parch      fare  alone  Cherbourg  Queenstown  \
455         1   29      0      0    7.8958      1          1           0   
380         1   42      0      0  227.5250      1          1           0   
492         0   55      0      0   30.5000      1          0           0   
55          1    0      0      0   35.5000      1          0           0   
243         0   22      0      0    7.1250      1          0           0   

     Southampton  female  male  
455            0       0     1  
380            0       1     0  
492            1       0     1  
55             1       0     1  
243            1       0     1

# Isolate the target

In [50]:
# we know what our X and y are, let's be explicit about defining them
X_train = train.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_train = train.survived

X_val = validate.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_val = validate.survived

X_test = test.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_test = test.survived

### 1. Fit a K-Nearest Neighbors classifier to your training sample and transform (i.e. make predictions on the training sample)

In [51]:
#Create KNN Object
knn = KNeighborsClassifier()
knn

KNeighborsClassifier()

In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [52]:
#Fit the Model to the Training Data
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [53]:
#Make Predictions
y_preds = knn.predict(X_train)
y_preds

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,

### 2. Evaluate your results using the model score, confusion matrix, and classification report.



In [54]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.76


In [55]:
#confusion matrix
cm = confusion_matrix(y_train, y_preds)
cm

array([[268,  61],
       [ 65, 140]])

In [57]:
#classification report
pd.DataFrame(classification_report(y_train, y_preds, output_dict=True))

0           1  accuracy   macro avg  weighted avg
precision    0.804805    0.696517  0.764045    0.750661      0.763234
recall       0.814590    0.682927  0.764045    0.748758      0.764045
f1-score     0.809668    0.689655  0.764045    0.749661      0.763595
support    329.000000  205.000000  0.764045  534.000000    534.000000

In [ ]:
# OR

In [56]:
print(classification_report(y_train, y_preds))

              precision    recall  f1-score   support

           0       0.80      0.81      0.81       329
           1       0.70      0.68      0.69       205

    accuracy                           0.76       534
   macro avg       0.75      0.75      0.75       534
weighted avg       0.76      0.76      0.76       534



### 3.Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.



In [24]:
evaluate.print_classification_metrics(y_train, y_preds)

Accuracy: 0.7640449438202247
True Positive Rate: 0.6829268292682927
False Positive Rate: 0.18541033434650456
True Negative Rate: 0.8145896656534954
False Negative Rate: 0.3170731707317073
Precision: 0.6965174129353234
Recall: 0.6829268292682927
F1 Score: 0.6896551724137931
Support (0): 205
Support (1): 329


### 4.Run through steps 1-3 setting k to 10



In [25]:
knn = KNeighborsClassifier(n_neighbors=10)

In [26]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [27]:
y_preds = knn.predict(X_train)
y_preds

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [28]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.71


In [29]:
confusion_matrix(y_train, y_preds)

array([[292,  37],
       [118,  87]])

In [30]:
print(classification_report(y_train, y_preds))

              precision    recall  f1-score   support

           0       0.71      0.89      0.79       329
           1       0.70      0.42      0.53       205

    accuracy                           0.71       534
   macro avg       0.71      0.66      0.66       534
weighted avg       0.71      0.71      0.69       534



In [31]:
evaluate.print_classification_metrics(y_train, y_preds)

Accuracy: 0.7097378277153558
True Positive Rate: 0.424390243902439
False Positive Rate: 0.11246200607902736
True Negative Rate: 0.8875379939209727
False Negative Rate: 0.5756097560975609
Precision: 0.7016129032258065
Recall: 0.424390243902439
F1 Score: 0.5288753799392097
Support (0): 205
Support (1): 329


### 5.Run through steps 1-3 setting k to 20




In [32]:
knn = KNeighborsClassifier(n_neighbors=20)

In [33]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=20)

In [34]:
y_preds = knn.predict(X_train)
y_preds


array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [35]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.69


In [36]:
confusion_matrix(y_train, y_preds)

array([[274,  55],
       [108,  97]])

In [37]:
print(classification_report(y_train, y_preds))

              precision    recall  f1-score   support

           0       0.72      0.83      0.77       329
           1       0.64      0.47      0.54       205

    accuracy                           0.69       534
   macro avg       0.68      0.65      0.66       534
weighted avg       0.69      0.69      0.68       534



In [38]:
evaluate.print_classification_metrics(y_train, y_preds)

Accuracy: 0.6947565543071161
True Positive Rate: 0.47317073170731705
False Positive Rate: 0.16717325227963525
True Negative Rate: 0.8328267477203647
False Negative Rate: 0.526829268292683
Precision: 0.6381578947368421
Recall: 0.47317073170731705
F1 Score: 0.5434173669467788
Support (0): 205
Support (1): 329


### 6.What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?



In [39]:
pred_dict = {
    'model': [],
    'accuracy': [],
    'true_positive_rate': [],
    'false_positive_rate': [],
    'true_negative_rate': [],
    'false_negative_rate': [],
    'precision': [],
    'recall': [],
    'f1_score': [],
    'support_0': [],
    'support_1': []
}

for n in [5, 10, 20]:
    knn = KNeighborsClassifier(n_neighbors=n)
    
    knn.fit(X_train, y_train)
    
    y_preds = knn.predict(X_train)
    
    TN, FP, FN, TP = confusion_matrix(y_train, y_preds).ravel()
    ALL = TP + TN + FP + FN
    
    accuracy = (TP + TN)/ALL
    true_positive_rate = TP/(TP+FN)
    false_positive_rate = FP/(FP+TN)
    true_negative_rate = TN/(TN+FP)
    false_negative_rate = FN/(FN+TP)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*(precision*recall)/(precision+recall)
    support_pos = TP + FN
    support_neg = FP + TN
    
    pred_dict['model'].append(f'knn_n_{n}')
    pred_dict['accuracy'].append(accuracy)
    pred_dict['true_positive_rate'].append(true_positive_rate)
    pred_dict['false_positive_rate'].append(false_positive_rate)
    pred_dict['true_negative_rate'].append(true_negative_rate)
    pred_dict['false_negative_rate'].append(false_negative_rate)
    pred_dict['precision'].append(precision)
    pred_dict['recall'].append(recall)
    pred_dict['f1_score'].append(f1_score)
    pred_dict['support_0'].append(support_pos)
    pred_dict['support_1'].append(support_neg)


In [40]:
pd.DataFrame(pred_dict)


model  accuracy  true_positive_rate  false_positive_rate  \
0   knn_n_5  0.764045            0.682927             0.185410   
1  knn_n_10  0.709738            0.424390             0.112462   
2  knn_n_20  0.694757            0.473171             0.167173   

   true_negative_rate  false_negative_rate  precision    recall  f1_score  \
0            0.814590             0.317073   0.696517  0.682927  0.689655   
1            0.887538             0.575610   0.701613  0.424390  0.528875   
2            0.832827             0.526829   0.638158  0.473171  0.543417   

   support_0  support_1  
0        205        329  
1        205        329  
2        205        329

In [41]:
pd.DataFrame(pred_dict).T

0         1         2
model                 knn_n_5  knn_n_10  knn_n_20
accuracy             0.764045  0.709738  0.694757
true_positive_rate   0.682927   0.42439  0.473171
false_positive_rate   0.18541  0.112462  0.167173
true_negative_rate    0.81459  0.887538  0.832827
false_negative_rate  0.317073   0.57561  0.526829
precision            0.696517  0.701613  0.638158
recall               0.682927   0.42439  0.473171
f1_score             0.689655  0.528875  0.543417
support_0                 205       205       205
support_1                 329       329       329

In [42]:
train_pred_df = pd.DataFrame(pred_dict).T
train_pred_df.columns = train_pred_df.iloc[0]
train_pred_df = train_pred_df.drop(train_pred_df.index[0])
train_pred_df

model                 knn_n_5  knn_n_10  knn_n_20
accuracy             0.764045  0.709738  0.694757
true_positive_rate   0.682927   0.42439  0.473171
false_positive_rate   0.18541  0.112462  0.167173
true_negative_rate    0.81459  0.887538  0.832827
false_negative_rate  0.317073   0.57561  0.526829
precision            0.696517  0.701613  0.638158
recall               0.682927   0.42439  0.473171
f1_score             0.689655  0.528875  0.543417
support_0                 205       205       205
support_1                 329       329       329

### 7.Which model performs best on our out-of-sample data from validate?


In [43]:
pred_dict = {
    'model': [],
    'accuracy': [],
    'true_positive_rate': [],
    'false_positive_rate': [],
    'true_negative_rate': [],
    'false_negative_rate': [],
    'precision': [],
    'recall': [],
    'f1_score': [],
    'support_0': [],
    'support_1': []
}

for n in [5, 10, 20]:
    knn = KNeighborsClassifier(n_neighbors=n)
    
    knn.fit(X_train, y_train)
    
    y_preds = knn.predict(X_val)
    
    TN, FP, FN, TP = confusion_matrix(y_val, y_preds).ravel()
    ALL = TP + TN + FP + FN
    
    accuracy = (TP + TN)/ALL
    true_positive_rate = TP/(TP+FN)
    false_positive_rate = FP/(FP+TN)
    true_negative_rate = TN/(TN+FP)
    false_negative_rate = FN/(FN+TP)
    precision = TP/(TP+FP)
    recall = TP/(TP+FN)
    f1_score = 2*(precision*recall)/(precision+recall)
    support_pos = TP + FN
    support_neg = FP + TN
    
    pred_dict['model'].append(f'knn_n_{n}')
    pred_dict['accuracy'].append(accuracy)
    pred_dict['true_positive_rate'].append(true_positive_rate)
    pred_dict['false_positive_rate'].append(false_positive_rate)
    pred_dict['true_negative_rate'].append(true_negative_rate)
    pred_dict['false_negative_rate'].append(false_negative_rate)
    pred_dict['precision'].append(precision)
    pred_dict['recall'].append(recall)
    pred_dict['f1_score'].append(f1_score)
    pred_dict['support_0'].append(support_pos)
    pred_dict['support_1'].append(support_neg)

In [44]:
val_pred_df = pd.DataFrame(pred_dict).T
val_pred_df.columns = val_pred_df.iloc[0]
val_pred_df = val_pred_df.drop(val_pred_df.index[0])
val_pred_df


model                 knn_n_5  knn_n_10  knn_n_20
accuracy             0.651685  0.629213  0.674157
true_positive_rate   0.558824  0.367647       0.5
false_positive_rate  0.290909  0.209091  0.218182
true_negative_rate   0.709091  0.790909  0.781818
false_negative_rate  0.441176  0.632353       0.5
precision            0.542857  0.520833  0.586207
recall               0.558824  0.367647       0.5
f1_score             0.550725  0.431034  0.539683
support_0                  68        68        68
support_1                 110       110       110