<div style="background-color: lightblue; padding: 40px; font-size: 40px;">
            Logistic Regression
</div>

Logistic Regression is a statistical method and a type of regression analysis that is used for predicting the probability of a binary outcome. In other words, it's a technique used to model the relationship between a set of independent variables (also known as features or predictors) and a binary dependent variable (also known as the outcome or response). The outcome variable typically takes one of two values, often represented as 0 and 1.

Despite its name, logistic regression is not used for regression tasks in the traditional sense of predicting continuous numeric values. Instead, it's a classification algorithm suited for problems where the goal is to determine the likelihood of an instance belonging to a particular class or category.



Used for predicting discrete outcomes (binomial and multinomial)



In [66]:
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


#User-Defined Function-importing the functions for fetching the data:
import acquire
from acquire import new_titanic_data
#User-Defined Function-importing functions for prepping the data that's fetched and for splitting the data:
import prepare
from prepare import prep_titanic_for_dt, split_function
#User-Defined Function-importing the functions for classification_metrics
import evaluate



# ignore warnings
import warnings
warnings.filterwarnings("ignore")


## Use Titanic dataset

In [79]:
# Acquire data
titanic = prep_titanic_for_dt(new_titanic_data())
titanic.head()

survived  age  sibsp  parch     fare  alone  Cherbourg  Queenstown  \
0         0   22      1      0   7.2500      0          0           0   
1         1   38      1      0  71.2833      0          1           0   
2         1   26      0      0   7.9250      1          0           0   
3         1   35      1      0  53.1000      0          0           0   
4         0   35      0      0   8.0500      1          0           0   

   Southampton  female  male  
0            1       0     1  
1            0       1     0  
2            1       1     0  
3            1       1     0  
4            1       0     1

In [80]:
titanic_df= new_titanic_data()
titanic_df

passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
0               0         0       3    male  22.0      1      0   7.2500   
1               1         1       1  female  38.0      1      0  71.2833   
2               2         1       3  female  26.0      0      0   7.9250   
3               3         1       1  female  35.0      1      0  53.1000   
4               4         0       3    male  35.0      0      0   8.0500   
..            ...       ...     ...     ...   ...    ...    ...      ...   
886           886         0       2    male  27.0      0      0  13.0000   
887           887         1       1  female  19.0      0      0  30.0000   
888           888         0       3  female   NaN      1      2  23.4500   
889           889         1       1    male  26.0      0      0  30.0000   
890           890         0       3    male  32.0      0      0   7.7500   

    embarked   class  deck  embark_town  alone  
0          S   Third  None  Southampton      0  
1          C   First     C    Cherbourg      0  
2          S   Third  None  Southampton      1  
3          S   First     C  Southampton      0  
4          S   Third  None  Southampton      1  
..       ...     ...   ...          ...    ...  
886        S  Second  None  Southampton      1  
887        S   First     B  Southampton      1  
888        S   Third  None  Southampton      0  
889        C   First     C    Cherbourg      1  
890        Q   Third  None   Queenstown      1  

[891 rows x 13 columns]

In [81]:
titanic = prep_titanic_for_dt(titanic_df)
titanic

survived  age  sibsp  parch     fare  alone  Cherbourg  Queenstown  \
0           0   22      1      0   7.2500      0          0           0   
1           1   38      1      0  71.2833      0          1           0   
2           1   26      0      0   7.9250      1          0           0   
3           1   35      1      0  53.1000      0          0           0   
4           0   35      0      0   8.0500      1          0           0   
..        ...  ...    ...    ...      ...    ...        ...         ...   
886         0   27      0      0  13.0000      1          0           0   
887         1   19      0      0  30.0000      1          0           0   
888         0    0      1      2  23.4500      0          0           0   
889         1   26      0      0  30.0000      1          1           0   
890         0   32      0      0   7.7500      1          0           1   

     Southampton  female  male  
0              1       0     1  
1              0       1     0  
2              1       1     0  
3              1       1     0  
4              1       0     1  
..           ...     ...   ...  
886            1       0     1  
887            1       1     0  
888            1       1     0  
889            0       0     1  
890            0       0     1  

[891 rows x 11 columns]

In [82]:
# Train, validate, split data
train, validate, test = split_function(titanic, 'survived')

In [45]:
train.shape, validate.shape, test.shape

((534, 12), (178, 12), (179, 12))

In [71]:
train.head()

survived  age  sibsp  parch      fare  alone  Cherbourg  Queenstown  \
455         1   29      0      0    7.8958      1          1           0   
380         1   42      0      0  227.5250      1          1           0   
492         0   55      0      0   30.5000      1          0           0   
55          1    0      0      0   35.5000      1          0           0   
243         0   22      0      0    7.1250      1          0           0   

     Southampton  female  male  
455            0       0     1  
380            0       1     0  
492            1       0     1  
55             1       0     1  
243            1       0     1

In [73]:
# Defining  our X and y variables for train, validate and test data

X_train = train.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_train = train.survived

X_val = validate.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_val = validate.survived

X_test = test.drop(columns=['survived','female','male','Cherbourg','Queenstown','Southampton'])
y_test = test.survived

In [26]:
X_train.head()

pclass  age      fare
455       3   29    7.8958
380       1   42  227.5250
492       1   55   30.5000
55        1    0   35.5000
243       3   22    7.1250

In [ ]:
#or  target can be defined like this as well
#target = 'survived'

In [ ]:
#or  y variables can be defined like this as well
#y_train = train[target]
# y_validate = validate[target]
# y_test = test[target]

# y_train.head()

### 1. Create a model that includes only age, fare, and pclass. Does this model perform better than your baseline?



In [27]:
#defining the logistic regression model
logit=LogisticRegression(C=1,random_state=123)

In [28]:
#fit the model on train data
logit.fit(X_train,y_train)

LogisticRegression(C=1, random_state=123)

In [30]:
# use model to make predictions
y_pred=logit.predict(X_train)

In [31]:
#take a look at predictions
y_pred

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [32]:
#Look at the predicted probabilities for the first 10 observations
logit.predict_proba(X_train)[:10]

array([[0.77481375, 0.22518625],
       [0.27890946, 0.72109054],
       [0.45663058, 0.54336942],
       [0.27564844, 0.72435156],
       [0.7575134 , 0.2424866 ],
       [0.62804113, 0.37195887],
       [0.69557916, 0.30442084],
       [0.77718946, 0.22281054],
       [0.41460634, 0.58539366],
       [0.69845405, 0.30154595]])

In [33]:
logit.classes_

array([0, 1])

In [ ]:
#view raw probabilities(output from the model)
y_pred_proba=logit.predict_proba(X_train)

In [41]:
# create algorithm object ############
logit1 = LogisticRegression(C=1, random_state=42, intercept_scaling=1, solver='liblinear')

# fit model with age, pclass and fare as only features
logit1.fit(X_train[['age', 'pclass', 'fare']], y_train)

# compute accuracy
train_accuracy = logit1.score(X_train[['age', 'pclass', 'fare']], y_train)

# compare this model with baseline
print(f'Train Accuracy: {train_accuracy}')
print(f'Baseline Accuracy: {baseline_accuracy}')


Train Accuracy: 0.6816479400749064
Baseline Accuracy: 0.6161048689138576


In [ ]:
# OR

In [83]:
y_train.value_counts()


survived
0    329
1    205
Name: count, dtype: int64

In [84]:
(y_train == 0).mean()

0.6161048689138576

In [85]:
X_train.head()

age  sibsp  parch      fare  alone
455   29      0      0    7.8958      1
380   42      0      0  227.5250      1
492   55      0      0   30.5000      1
55     0      0      0   35.5000      1
243   22      0      0    7.1250      1

In [ ]:
features1 = ['age','fare','pclass']
X_train[features1].head()

### 2. Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model.



In [47]:
# we know what our X and y are, let's be explicit about defining them
X1_train = train.drop(columns=['survived','Cherbourg','Queenstown','Southampton','sibsp','parch','alone'])
y1_train = train.survived

X1_val = validate.drop(columns=['survived','Cherbourg','Queenstown','Southampton','sibsp','parch','alone'])
y1_val = validate.survived

X1_test = test.drop(columns=['survived','Cherbourg','Queenstown','Southampton','sibsp','parch','alone'])
y1_test = test.survived

In [48]:
X1_train.head()

pclass  age      fare  female  male
455       3   29    7.8958       0     1
380       1   42  227.5250       1     0
492       1   55   30.5000       0     1
55        1    0   35.5000       0     1
243       3   22    7.1250       0     1

In [50]:
X1_train.shape,X1_val.shape,X1_test.shape

((534, 5), (178, 5), (179, 5))

In [52]:
# used dummy data 

# create algorithm object
logit2 = LogisticRegression(C=1, random_state=42, intercept_scaling=1, solver='liblinear')

# fit model with age, pclass, fare and sex_male as only features
#logit2.fit(X_train[['age', 'pclass', 'fare', 'sex']], y_train)
logit2.fit(X1_train[['age', 'pclass', 'fare', 'female','male']], y1_train)
    
# fit model with age, pclass and fare as only features
#logit1.fit(X_train[['age', 'pclass', 'fare']], y_train)


# compute accuracy
train_accuracy = logit2.score(X1_train[['age', 'pclass', 'fare', 'female','male']], y1_train)

# compare this model with baseline
print(f'Train Accuracy: {train_accuracy}')
print(f'Baseline Accuracy: {baseline_accuracy}')

Train Accuracy: 0.7921348314606742
Baseline Accuracy: 0.6161048689138576


### 3. Try out other combinations of features and models.



In [57]:
LogisticRegression?

In [53]:
# Test model with all features

# create algorithm object
logit3 = LogisticRegression(C=1, random_state=42, intercept_scaling=1, solver='liblinear')

# fit model with all features
logit3.fit(X1_train, y1_train)

# compute accuracy
train_accuracy = logit3.score(X1_train, y1_train)

# compare this model with baseline
print(f'Train Accuracy: {train_accuracy}')
print(f'Baseline Accuracy: {baseline_accuracy}')

Train Accuracy: 0.7921348314606742
Baseline Accuracy: 0.6161048689138576


In [54]:
# Try changing 'solver' to 'lbfgs' feature

# create algorithm object
logit4 = LogisticRegression(C=1, random_state=42, intercept_scaling=1, solver='lbfgs')

# fit model with all features
logit4.fit(X1_train, y1_train)

# compute accuracy
train_acc4 = logit4.score(X1_train, y1_train)

# compare this model with baseline
print(f'Train Accuracy: {train_acc4}')
print(f'Baseline Accuracy: {baseline_accuracy}')

Train Accuracy: 0.7790262172284644
Baseline Accuracy: 0.6161048689138576


In [56]:
# Try changing 'class_weight' to 'balanced'

# create algorithm object
logit5 = LogisticRegression(C=1, class_weight='balanced', random_state=42, intercept_scaling=1, solver='lbfgs')

# fit model with all features
logit5.fit(X1_train, y1_train)

# compute accuracy
train_acc5 = logit5.score(X1_train, y1_train)

# compare this model with baseline
print(f'Train Accuracy: {train_acc5}')
print(f'Baseline Accuracy: {baseline_accuracy}')

Train Accuracy: 0.7808988764044944
Baseline Accuracy: 0.6161048689138576


In [58]:
# Try changing c-value (regularization strength) from 1 to 0.1

# create algorithm object
logit6 = LogisticRegression(C=0.1, random_state=123, intercept_scaling=1, solver='lbfgs')

# fit model with all features
logit6.fit(X1_train, y1_train)

# compute accuracy
train_acc6 = logit6.score(X1_train, y1_train)

# compare this model with baseline
print(f'Train Accuracy: {train_acc6}')
print(f'Baseline Accuracy: {baseline_accuracy}')


Train Accuracy: 0.7865168539325843
Baseline Accuracy: 0.6161048689138576


### 4.Use you best 3 models to predict and evaluate on your validate sample.



In [59]:
# use logit# to make predictions for the X_validate observations
y_val_pred3 = logit3.predict(X1_val)
# compute accuracy
val_acc3 = logit3.score(X1_val, y1_val)
# create a list and add to a dataframe at the end comparing all the models. 
model3 = [3, train_acc4, val_acc3]

y_val_pred5 = logit5.predict(X1_val)
val_acc5 = logit5.score(X1_val, y1_val) 
model5 = [5, train_acc5, val_acc5]

y_val_pred6 = logit6.predict(X1_val)
val_acc6 = logit6.score(X1_val, y1_val) 
model6 = [6, train_acc6, val_acc6]

pd.DataFrame([model3, model5, model6], columns=['model', 'in-sample accuracy', 'out-of-sample accuracy'])

model  in-sample accuracy  out-of-sample accuracy
0      3            0.779026                0.775281
1      5            0.780899                0.764045
2      6            0.786517                0.780899

### 5.Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train?

In [63]:
print('Coefficient: \n', logit6.coef_)
print('Intercept: \n', logit6.intercept_)

Coefficient: 
 [[-0.79956496 -0.00879672  0.00170796  1.0610135  -1.06092475]]
Intercept: 
 [1.74710913]


In [62]:
# Validate model 6

y_pred6 = logit6.predict(X1_val)
print("Model 6: solver = lbfgs, c = 1")
# accuracy of model 6
print('Accuracy: {:.2f}'.format(logit6.score(X1_val, y1_val)))
# confusion matrix of model 6
print(confusion_matrix(y1_val, y_pred6))
# classification report of model 1
print(classification_report(y1_val, y_pred6))

Model 6: solver = lbfgs, c = 1
Accuracy: 0.78
[[91 19]
 [20 48]]
              precision    recall  f1-score   support

           0       0.82      0.83      0.82       110
           1       0.72      0.71      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178



In [64]:
# Test Model 6

y_pred6 = logit6.predict(X1_test)
y_pred_proba = logit6.predict_proba(X1_test)
print("Model 6: solver = lbfgs, c = 1")
print('Accuracy: {:.2f}'.format(logit6.score(X1_test, y1_test)))
print(confusion_matrix(y1_test, y_pred6))
print(classification_report(y1_test, y_pred6))

Model 6: solver = lbfgs, c = 1
Accuracy: 0.78
[[93 17]
 [23 46]]
              precision    recall  f1-score   support

           0       0.80      0.85      0.82       110
           1       0.73      0.67      0.70        69

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.76       179
weighted avg       0.77      0.78      0.77       179

